### ISSUE TITLE
No Windows support for latest version for RustDDS

### ISSUE THREAD

**Issue by julian-engelberger-bl** [jhelovuo/RustDDS#264]
Hi,
I tried to compile the latest version of RustDDS, however `src/mio_source/mod.rs` uses `os::fd::{AsRawFd, FromRawFd, OwnedFd}` which is not available under Windows.

**Comment by jhelovuo** [comment]
Yes, this is a semi-accidental change due to mio-0.8 support.

We need to send notifications from the background thread to the application thread. In order to poll these notifications with mio-0.8, there needs to be an OS file descriptor that can be polled to detect a notification. We use a socketpair to do this, so a dummy piece of data is sent over a socketpair. This can then be polled with `mio` to detect that there is an event available.

The setup of socket pairs to do this was not fully portable from Linux to Windows. Do you have means to fix this and propose a PR? It should be sufficient to fix only the `mio_source` module.

**Comment by phil-opp** [comment]
Was this fixed by https://github.com/jhelovuo/RustDDS/pull/290?

**Comment by kandersonpeng** [comment]
Sadly no.  With a new project ("cargo new dds_test"), rust 1.71.0 (stable, not nightly), on Windows 10, with the ONLY dependency being rustdds="0.8.4" you get this error message:

```
error[E0432]: unresolved import `std::os::fd`
 --> C:\Users\Kevin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustdds-0.8.4\src\mio_source.rs:4:7
  |
4 |   os::fd::{AsRawFd, FromRawFd, OwnedFd},
  |       ^^ could not find `fd` in `os`

error[E0599]: no function or associated item named `from_raw_fd` found for struct `mio::net::TcpStream` in the current scope
  --> C:\Users\Kevin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustdds-0.8.4\src\mio_source.rs:53:57
   |
53 |   let rec_mio_socket = unsafe { mio_08::net::TcpStream::from_raw_fd(rec_sps.as_raw_fd()) };
   |                                                         ^^^^^^^^^^^ function or associated item not found in `TcpStream`

error[E0599]: no method named `as_raw_fd` found for struct `socketpair::SocketpairStream` in the current scope
  --> C:\Users\Kevin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustdds-0.8.4\src\mio_source.rs:53:77
   |
53 |   let rec_mio_socket = unsafe { mio_08::net::TcpStream::from_raw_fd(rec_sps.as_raw_fd()) };
   |                                                                             ^^^^^^^^^ method not found in `SocketpairStream`

error[E0599]: no function or associated item named `from_raw_fd` found for struct `mio::net::TcpStream` in the current scope
  --> C:\Users\Kevin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustdds-0.8.4\src\mio_source.rs:54:58
   |
54 |   let send_mio_socket = unsafe { mio_08::net::TcpStream::from_raw_fd(send_sps.as_raw_fd()) };
   |                                                          ^^^^^^^^^^^ function or associated item not found in `TcpStream`

error[E0599]: no method named `as_raw_fd` found for struct `socketpair::SocketpairStream` in the current scope
  --> C:\Users\Kevin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustdds-0.8.4\src\mio_source.rs:54:79
   |
54 |   let send_mio_socket = unsafe { mio_08::net::TcpStream::from_raw_fd(send_sps.as_raw_fd()) };
   |                                                                               ^^^^^^^^^ method not found in `SocketpairStream`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `rustdds` (lib) due to 5 previous errors
```
So I don't know what people are compiling, but with a very basic test, it doesn't build, even with no code present except the dependency.

What's the latest version that actually builds in Windows?  0.7.x?

**Comment by kandersonpeng** [comment]
My previous comment was useless.  When you specify the dependency to the github repository, it appears to build.  to do that in Cargo.toml, use a line similar to this:
```
rustdds= { git="https://github.com/jhelovuo/RustDDS.git" }
```
Seems to build now from the latest master.  Probably that PR that did it, but it's not released either, so you can't pull just from crates.io.

**Comment by samcarey** [comment]
The master branch works for me on Windows. Perhaps it's time for a minor version release on crates.io?
